# Generated by Django 4.2.6 on 2023-10-31 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderappemailpass', models.CharField(max_length=50)),
                ('senderemail', models.EmailField(max_length=50)),
                ('sendingdate', models.CharField(default='<function now at 0x000001F23ED21300>', max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
