# Generated by Django 4.2.6 on 2023-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seendeemmail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailsender',
            old_name='senderemail',
            new_name='receiveremail',
        ),
        migrations.RemoveField(
            model_name='mailsender',
            name='senderappemailpass',
        ),
        migrations.AddField(
            model_name='mailsender',
            name='msg',
            field=models.CharField(default='hey', max_length=99999),
        ),
        migrations.AlterField(
            model_name='mailsender',
            name='sendingdate',
            field=models.CharField(default='<function now at 0x00000278DE165300>', max_length=30),
        ),
    ]
