# Generated by Django 4.2.6 on 2023-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seendeemmail', '0002_rename_senderemail_mailsender_receiveremail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailsender',
            name='msg',
            field=models.CharField(max_length=99999),
        ),
        migrations.AlterField(
            model_name='mailsender',
            name='sendingdate',
            field=models.CharField(default='<function now at 0x0000024BE1965300>', max_length=30),
        ),
    ]
