# Generated by Django 5.0.1 on 2024-01-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seendeemmail', '0003_alter_mailsender_msg_alter_mailsender_sendingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailsender',
            name='title',
            field=models.CharField(default='You not given title of message', max_length=100),
        ),
        migrations.AlterField(
            model_name='mailsender',
            name='sendingdate',
            field=models.CharField(default='<function now at 0x000001C71E358180>', max_length=30),
        ),
    ]
